---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"

  - name: install apache2 package 
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache 
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for almalinux
    dnf:
      update_cache: yes
    when: ansible_distribution_version == "almalinux"

  - name: install apache2 package for almalinux
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "almalinux"

  - name: add php support for apache for almalinux
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "almalinux"
