---

- hosts: all
  become: true
  tasks:


  - name: install apache and php
    package:
      name:
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes
 
- hosts: web_servers
  become: true
  tasks:

  - name: install apache package (Arch Linux)
    tags: apache,arch,apache
    pacman:
      name:
        - apache
        - php
      state: latest
    when: ansible_distribution == "Archlinux"

  - name: install apache2 package (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: create web root directory for Arch Linux
    file:
      path: /var/www/html
      state: directory
      owner: root
      group: root
      mode: 0755
    when: ansible_distribution == "Archlinux"

  - name: copy html file
    tags: apache,apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
